import { Resource } from "./types";

// NOTE: These are fictional demo resources for Santa Clara, CA.
// They are NOT real organizations. Availability is not guaranteed.
export const resources: Resource[] = [
  {
    id: "safestay-santa-clara",
    name: "SafeStay Santa Clara",
    type: ["Shelter tonight", "Case management"],
    description: "Emergency overnight shelter and case management support.",
    distanceMiles: 1.1,
    intakeHours: "6 PM to 9 PM",
    openTonight: true,
    walkIns: true,
    requiresId: false,
    allowsPets: true,
    familyFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Walking", "Public transit"],
    phone: "(408) 555-0134",
    address: "Demo address near Santa Clara Civic Center",
    whatToBring: ["Backpack", "Any ID if available", "Pet leash if bringing a dog"],
    notes: "Call before arrival to confirm space.",
    reliability: "Medium",
  },
  {
    id: "hope-warming-center",
    name: "Hope Warming Center",
    type: ["Shelter tonight"],
    description: "Overnight warming center with basic supplies.",
    distanceMiles: 2.4,
    intakeHours: "7 PM to 7 AM",
    openTonight: true,
    walkIns: true,
    requiresId: false,
    allowsPets: false,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish", "Vietnamese"],
    transportation: ["Public transit"],
    phone: "(408) 555-0198",
    address: "Demo address near El Camino Real",
    whatToBring: ["Warm clothing", "Any medication", "Phone charger"],
    notes: "Pets may be limited to service animals.",
    reliability: "Medium",
  },
  {
    id: "family-bridge-housing",
    name: "Family Bridge Housing",
    type: ["Shelter tonight", "Case management"],
    description: "Short-term housing support for families with children.",
    distanceMiles: 3.2,
    intakeHours: "9 AM to 5 PM",
    openTonight: false,
    walkIns: false,
    requiresId: true,
    allowsPets: false,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Public transit", "Car"],
    phone: "(408) 555-0177",
    address: "Demo address near Central Park",
    whatToBring: [
      "ID if available",
      "Birth certificates if available",
      "School records if available",
    ],
    notes: "Best for families planning ahead.",
    reliability: "High",
  },
  {
    id: "new-start-document-clinic",
    name: "New Start Document Clinic",
    type: ["ID/document help", "Case management"],
    description:
      "Helps replace ID, birth certificates, benefits paperwork, and mail access.",
    distanceMiles: 1.8,
    intakeHours: "10 AM to 4 PM",
    openTonight: false,
    walkIns: true,
    requiresId: false,
    allowsPets: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Walking", "Public transit"],
    phone: "(408) 555-0112",
    address: "Demo address near Santa Clara University",
    whatToBring: [
      "Any old documents",
      "Photo of documents if available",
      "Mail or proof of name if available",
    ],
    notes: "Good follow-up resource if ID is missing.",
    reliability: "High",
  },
  {
    id: "community-meal-hub",
    name: "Community Meal Hub",
    type: ["Food"],
    description: "Daily hot meals and pantry bags.",
    distanceMiles: 0.7,
    intakeHours: "11 AM to 2 PM, 5 PM to 7 PM",
    openTonight: true,
    walkIns: true,
    requiresId: false,
    allowsPets: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Walking", "Public transit"],
    phone: "(408) 555-0161",
    address: "Demo address near Franklin Square",
    whatToBring: ["Reusable bag if available"],
    notes: "No appointment needed.",
    reliability: "High",
  },
  {
    id: "fresh-start-hygiene-center",
    name: "Fresh Start Hygiene Center",
    type: ["Shower/laundry"],
    description: "Showers, laundry, hygiene kits, and charging stations.",
    distanceMiles: 2.0,
    intakeHours: "8 AM to 6 PM",
    openTonight: false,
    walkIns: true,
    requiresId: false,
    allowsPets: false,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Public transit"],
    phone: "(408) 555-0184",
    address: "Demo address near The Alameda",
    whatToBring: ["Change of clothes if available"],
    notes: "Laundry slots may fill up.",
    reliability: "High",
  },
  {
    id: "mobile-health-van",
    name: "Mobile Health Van",
    type: ["Medical help"],
    description: "Basic health screenings, wound care, and referrals.",
    distanceMiles: 1.5,
    intakeHours: "12 PM to 5 PM",
    openTonight: false,
    walkIns: true,
    requiresId: false,
    allowsPets: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish", "Vietnamese"],
    transportation: ["Walking", "Public transit"],
    phone: "(408) 555-0142",
    address: "Demo location rotating near Santa Clara Library",
    whatToBring: [
      "Medication list if available",
      "Insurance card if available but not required",
    ],
    notes: "Not for emergencies.",
    reliability: "Medium",
  },
  {
    id: "transit-help-desk",
    name: "Transit Help Desk",
    type: ["Transportation help", "Case management"],
    description:
      "Bus passes and transportation support for appointments and shelter intake.",
    distanceMiles: 1.3,
    intakeHours: "9 AM to 6 PM",
    openTonight: true,
    walkIns: true,
    requiresId: false,
    allowsPets: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Walking", "Public transit"],
    phone: "(408) 555-0129",
    address: "Demo address near Santa Clara Transit Center",
    whatToBring: ["Appointment details if available"],
    notes: "Limited daily passes available.",
    reliability: "Medium",
  },
];
