import { Resource } from "./types";

// Seeded from publicly listed Santa Clara County resources. These are real
// organizations, but bed space, hours, and intake rules can change quickly.
// Always call to confirm before traveling.
export const resources: Resource[] = [
  {
    id: "boccardo-reception-center",
    name: "Boccardo Reception Center (HomeFirst)",
    type: ["Shelter tonight", "Case management"],
    description:
      "Large emergency shelter with meals, showers, and supportive services for adults and some families.",
    distanceMiles: 6.2,
    intakeHours: "24/7 shelter; line by 3:30 PM for beds",
    openTonight: true,
    walkIns: true,
    requiresId: null,
    allowsPets: true,
    familyFriendly: true,
    wheelchairAccessible: null,
    languages: [],
    transportation: ["Public transit", "Car"],
    phone: "(408) 539-2100",
    address: "2011 Little Orchard Street, San Jose, CA 95125",
    whatToBring: ["Any ID or paperwork you have", "Medications", "Phone charger if available"],
    notes:
      "HomeFirst lists nightly shelter and services here. Public pet listings say pets are welcome; call ahead to confirm current pet rules.",
    reliability: "Medium",
  },
  {
    id: "montgomery-street-inn",
    name: "Montgomery Street Inn (LifeMoves)",
    type: ["Shelter tonight", "Case management"],
    description:
      "Emergency and transitional housing for adult men with case management, veterans' services, and medical respite care.",
    distanceMiles: 4.8,
    intakeHours: "Call for screening and bed access",
    openTonight: true,
    walkIns: false,
    requiresId: true,
    allowsPets: false,
    familyFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Public transit", "Car"],
    phone: "(408) 271-5160",
    address: "358 North Montgomery Street, San Jose, CA 95110",
    whatToBring: ["Photo ID", "Any service animal paperwork if applicable", "Essential belongings"],
    notes:
      "211 listing says adult men only. Pet accommodation is limited to service animals with documentation.",
    reliability: "High",
  },
  {
    id: "georgia-travis-house",
    name: "Georgia Travis House (LifeMoves)",
    type: ["Shelter tonight", "Case management"],
    description:
      "Emergency housing for women and families with case management, counseling, and child-focused support.",
    distanceMiles: 4.9,
    intakeHours: "Call for intake information",
    openTonight: true,
    walkIns: false,
    requiresId: true,
    allowsPets: false,
    familyFriendly: true,
    wheelchairAccessible: null,
    womenOnly: true,
    languages: [],
    transportation: ["Public transit", "Car"],
    phone: "(408) 271-1630",
    address: "260 Commercial Street, San Jose, CA 95112",
    whatToBring: ["Photo ID if available", "Children's records if available", "Medications", "Essential belongings"],
    notes:
      "Public listing says the shelter serves women and families. Non-service pets are not accepted.",
    reliability: "High",
  },
  {
    id: "julian-street-inn",
    name: "Julian Street Inn (LifeMoves)",
    type: ["Shelter tonight", "Case management"],
    description:
      "Emergency and transitional housing for adults with a mental illness, with beds, meals, and supportive services.",
    distanceMiles: 4.4,
    intakeHours: "Call for information",
    openTonight: true,
    walkIns: false,
    requiresId: null,
    allowsPets: null,
    familyFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    transportation: ["Public transit", "Car"],
    phone: "(408) 271-0820",
    address: "546 West Julian Street, San Jose, CA 95110",
    whatToBring: ["Any referral or medical paperwork", "Medications", "Essential belongings"],
    notes:
      "211 listing says this site is for adults age 18+ with a mental illness. Public materials do not clearly list ID or pet requirements.",
    reliability: "High",
  },
  {
    id: "emmanuel-house",
    name: "Emmanuel House (The Salvation Army)",
    type: ["Shelter tonight", "Food"],
    description:
      "Overnight and transitional housing for men, with community meals served on site.",
    distanceMiles: 4.7,
    intakeHours: "Line at 3:30 PM; intake at 4:00 PM",
    openTonight: true,
    walkIns: true,
    requiresId: null,
    allowsPets: null,
    familyFriendly: false,
    wheelchairAccessible: null,
    languages: [],
    transportation: ["Public transit", "Walking"],
    phone: "(408) 282-1175",
    address: "405 North 4th Street, San Jose, CA 95112",
    whatToBring: ["Essential belongings", "Any paperwork you have", "Questions about meal times or bed availability"],
    notes:
      "Official program page says overnight housing is offered 365 days a year for men and beds line up at 3:30 PM.",
    reliability: "High",
  },
  {
    id: "marthas-kitchen",
    name: "Martha's Kitchen",
    type: ["Food"],
    description:
      "Hot meals and grocery distribution at the Story Road food hub.",
    distanceMiles: 8.4,
    intakeHours: "Mon/Fri noon to 1 PM; Tue/Wed 4 PM to 5 PM; Tue groceries 5 PM to 6 PM",
    openTonight: null,
    walkIns: true,
    requiresId: null,
    allowsPets: null,
    familyFriendly: true,
    wheelchairAccessible: null,
    languages: ["English", "Spanish"],
    transportation: ["Public transit", "Car"],
    phone: "(408) 293-6111",
    address: "749 Story Road, San Jose, CA 95122",
    whatToBring: ["Bag or cart if picking up groceries"],
    notes:
      "Meal times vary by day. Check the current weekly schedule before traveling.",
    reliability: "High",
  },
  {
    id: "dignity-on-wheels",
    name: "Dignity on Wheels (WeHOPE)",
    type: ["Shower/laundry"],
    description:
      "Mobile shower and laundry service for people experiencing homelessness.",
    distanceMiles: 5.5,
    intakeHours: "See current mobile schedule",
    openTonight: null,
    walkIns: true,
    requiresId: false,
    allowsPets: null,
    familyFriendly: true,
    wheelchairAccessible: true,
    languages: [],
    transportation: ["Public transit", "Walking", "Car"],
    phone: "(650) 330-8000",
    address: "Mobile service across Santa Clara County; check schedule for current stop",
    whatToBring: ["A change of clothes if available", "Laundry if needed"],
    notes:
      "Public listings describe free showers and laundry with wheelchair-accessible roll-in showers. Schedule and stop locations change.",
    reliability: "High",
  },
  {
    id: "vhc-homefirst-shelter",
    name: "Valley Health Center at HomeFirst Shelter",
    type: ["Medical help"],
    description:
      "Medical, psychiatry, psychology, and social work services for people experiencing homelessness.",
    distanceMiles: 6.2,
    intakeHours: "Same-day appointments",
    openTonight: false,
    walkIns: true,
    requiresId: null,
    allowsPets: null,
    familyFriendly: true,
    wheelchairAccessible: null,
    languages: [],
    transportation: ["Public transit", "Car"],
    phone: "(888) 334-1000",
    address: "2011 Little Orchard Street, San Jose, CA 95125",
    whatToBring: ["Medication list if available", "Any insurance information if available"],
    notes:
      "Santa Clara Valley Healthcare says you do not have to be staying at the shelter to receive care here.",
    reliability: "High",
  },
  {
    id: "here4you-hotline",
    name: "Here4You Hotline (Bill Wilson Center)",
    type: ["Transportation help", "Case management"],
    description:
      "County shelter hotline that matches people to temporary housing programs and can coordinate transportation to shelter.",
    distanceMiles: 1.0,
    intakeHours: "Daily 9 AM to 7 PM; weather-extreme hours may extend",
    openTonight: true,
    walkIns: false,
    requiresId: false,
    allowsPets: null,
    familyFriendly: true,
    wheelchairAccessible: null,
    languages: [],
    transportation: ["Walking", "Public transit", "Car"],
    phone: "(408) 385-2400",
    address: "Phone-based service for Santa Clara County",
    whatToBring: ["Current location", "Basic details about who needs shelter", "Phone if available"],
    notes:
      "Best first step when you need a shelter referral or transportation help. They also connect callers to other resources.",
    reliability: "High",
  },
  {
    id: "california-dmv-no-fee-id",
    name: "California DMV No-Fee ID Card Program",
    type: ["ID/document help"],
    description:
      "State ID program that may waive the fee for people experiencing homelessness when verified by a qualifying agency or nonprofit.",
    distanceMiles: 4.0,
    intakeHours: "Weekdays during DMV business hours",
    openTonight: false,
    walkIns: true,
    requiresId: null,
    allowsPets: null,
    familyFriendly: true,
    wheelchairAccessible: null,
    languages: [],
    transportation: ["Public transit", "Car"],
    phone: "1-800-777-0133",
    address: "Santa Clara DMV, 3665 Flora Vista Avenue, Santa Clara, CA 95051",
    whatToBring: ["Homeless verification form if available", "Any identity documents you have"],
    notes:
      "The DMV says people experiencing homelessness may qualify for a no-fee ID card with verification from a qualifying organization.",
    reliability: "High",
  },
];
